Public Class 主界面Form
    Private Sub Form1_Load(sender As Object, e As EventArgs)

    End Sub
    Private Sub 主界面Form_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    End Sub

    Private Sub 设置Button_Click(sender As Object, e As EventArgs) Handles 工作设置Button.Click
        Me.FolderBrowserDialog1.SelectedPath = "c:\"
        If Me.FolderBrowserDialog1.ShowDialog() = Windows.Forms.DialogResult.OK Then
            工作目录.Text = System.IO.Path.GetFullPath(Me.FolderBrowserDialog1.SelectedPath)
        End If

    End Sub

    Private Sub 启动Button_Click(sender As Object, e As EventArgs) Handles 启动Button.Click
        Me.OpenFileDialog1.RestoreDirectory = True
        If Me.OpenFileDialog1.ShowDialog = DialogResult.OK Then
            ansys启动程序.Text = Me.OpenFileDialog1.FileName()
        End If
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles 求解button.Click
        Dim input As Integer
        input = 1
        FileOpen(input, Me.工作目录.Text & "\input.mac", OpenMode.Output)
        '往下是温度场部分的仿真apdl
        PrintLine(input, "finish")
        PrintLine(input, "/clear")
        PrintLine(input, "/FILNAME," & Me.项目名称.Text)
        PrintLine(input, "/CWD," & Me.工作目录.Text)
        PrintLine(input, "!************280kA鐢佃В妲戒簩缁存ā鍨嬬儹鍦?********")
        PrintLine(input, "")
        PrintLine(input, "/CLEAR,START")
        PrintLine(input, "")
        PrintLine(input, "/prep7")
        PrintLine(input, "alls")
        PrintLine(input, "")
        PrintLine(input, "!*********0.瀹氫箟鍗曞厓*************")
        PrintLine(input, "ET,1,plane67       !2D thermo-electro")
        PrintLine(input, "ET,2,plane55       !2D thermo")
        PrintLine(input, "")
        PrintLine(input, "!*********1.鍑犱綍灏哄鍙傛暟**********")
        PrintLine(input, "!妲藉搴k")
        PrintLine(input, "Cll_wd=2020e-3")
        PrintLine(input, "")
        PrintLine(input, "!妲借啗瀹藉害 ok")
        PrintLine(input, "Cv_wd=1940e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗竴灞傚唴琛細纭呴吀閽欐澘 ok")
        PrintLine(input, "Lining1_hg=100e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗簩灞傚唴琛細淇濇俯鐮?鑰愰珮娓╃閰搁挋鏉?ok")
        PrintLine(input, "Lining2_hg=66e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗笁灞傚唴琛細闅旂儹鑰愮伀鐮?ok")
        PrintLine(input, "Lining3_hg=66e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗洓灞傚唴琛細闃叉笚鏂?ok")
        PrintLine(input, "Lining4_hg=185e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡楂樺害ok")
        PrintLine(input, "Cllb_hg=180e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡闀垮害 ok")
        PrintLine(input, "Cllb_wd=2130e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡绯婇珮搴?ok")
        PrintLine(input, "Clpt_hg=20e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬鐐潡瀹藉害 ok")
        PrintLine(input, "Cth_wd=1680e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬鐐潡楂樺害 ok")
        PrintLine(input, "Cth_hg=450e-3")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡楂樺害")
        PrintLine(input, "Scb_hg=820e-3")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡瀹藉害 ok")
        PrintLine(input, "Scb_wd=80e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婇珮搴?ok")
        PrintLine(input, "dgh_hg=550e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婁笂瀹?ok")
        PrintLine(input, "dgh_wd=50e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婁笅瀹?ok")
        PrintLine(input, "dgh_wd_dwn=260e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬瀹藉害 ok")
        PrintLine(input, "And_wd=1550e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬楂樺害 ok")
        PrintLine(input, "And_hg=370e-3 ")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬璺濅腑蹇冪嚎 ok")
        PrintLine(input, "Ad_2ad=90e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬璺濈渚ч儴鐐潡锛屽ぇ闈㈠姞宸ヨ窛绂?ok")
        PrintLine(input, "Swr_wd=300e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬閽㈡鎻掑叆闃虫瀬娣卞害 ok")
        PrintLine(input, "And_in=100e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅闂磋窛 ok")
        PrintLine(input, "Rod_2rod=300e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅楂樺害 ok")
        PrintLine(input, "Rod_hg=280e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅瀹藉害 ok")
        PrintLine(input, "Rod_dia=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅姊侀珮搴?ok")
        PrintLine(input, "Beam_hg=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!妯瀹藉害")
        PrintLine(input, "Beam_Wd=1050e-3")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!閾濆鏉嗗 ok")
        PrintLine(input, "Alrod_wd=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!閾濆鏉嗛珮搴?ok")
        PrintLine(input, "Alrod_hg=400e-3")
        PrintLine(input, "")
        PrintLine(input, "!姘у寲閾濊鐩栨枡鍘氬害ok")
        PrintLine(input, "Al2O3_hg=175e-3")
        PrintLine(input, "")
        PrintLine(input, "!閾濇按骞?ok")
        PrintLine(input, "Alu_hg=200e-3            ")
        PrintLine(input, "")
        PrintLine(input, "!鐢佃В璐ㄦ按骞?ok")
        PrintLine(input, "Elu_hg=175e-3   ")
        PrintLine(input, "")
        PrintLine(input, "!鏋佽窛 ok")
        PrintLine(input, "ACD=45e-3")
        PrintLine(input, "")
        PrintLine(input, "!******3.瀵规祦鎹㈢儹绯绘暟鐨勮瀹?*******")
        PrintLine(input, "!娓╁害琛ュ伩 ok")
        PrintLine(input, "TOFFST,273  ")
        PrintLine(input, "")
        PrintLine(input, "!鐔斾綋娓╁害 ok")
        PrintLine(input, "Tb=950")
        PrintLine(input, "")
        PrintLine(input, "!鐜娓╁害 ok")
        PrintLine(input, "Ta=35")
        PrintLine(input, "")
        PrintLine(input, "!鐑熸皵娓╁害锛屾哀鍖栭摑瑕嗙洊鏂欎笂闈㈢殑娓╁害 ok")
        PrintLine(input, "Td=97")
        PrintLine(input, "")
        PrintLine(input, "!鐔斾綋鍖轰笌澶栫晫瀵规祦鎹㈢儹绯绘暟 ok")
        PrintLine(input, "conv_sdt=20   ")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬妫掑尯涓庡鐣岀殑瀵规祦鎹㈢儹绯绘暟 ok")
        PrintLine(input, "conv_bar=10")
        PrintLine(input, "")
        PrintLine(input, "!鑰愮伀鍙婁繚娓╁尯涓庡鐣岀殑瀵规祦鎹㈢儹绯绘暟 ok")
        PrintLine(input, "conv_sdb=20")
        PrintLine(input, "")
        PrintLine(input, "!鐐夊簳涓庡鐣岀殑瀵规祦鎹㈢儹绯绘暟 ok")
        PrintLine(input, "conv_bt=10")
        PrintLine(input, "")
        PrintLine(input, "!鐐夐《涓庡鐣岀殑瀵规祦鎹㈢儹绯绘暟 ok")
        PrintLine(input, "conv_tp=25")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "                                                           ")
        PrintLine(input, "!********4.寤虹珛鍑犱綍妯″瀷***********")
        PrintLine(input, "!鍐呰‖寤烘āok")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg")
        PrintLine(input, "rectang,0,Cllb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Clpt_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡ok")
        PrintLine(input, "rectang,Cll_wd-Scb_wd,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Scb_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｉ紦绯?ok")
        PrintLine(input, "*get,kpnum,kp,0,count")
        PrintLine(input, "k,kpnum+1,Cll_wd-dgh_wd_dwn-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "k,kpnum+2,Cll_wd-dgh_wd_dwn-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "k,kpnum+3,Cll_wd-dgh_wd-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+dgh_hg")
        PrintLine(input, "k,kpnum+4,Cll_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+dgh_hg")
        PrintLine(input, "k,kpnum+5,Cll_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "a,kpnum+1,kpnum+2,kpnum+3,kpnum+4,kpnum+5")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!妲藉府")
        PrintLine(input, "sledg_dw_wd=20e-3+dgh_wd_dwn+Scb_wd")
        PrintLine(input, "sledg_dw_hg=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "sledg_mid_wd=dgh_wd_dwn+Scb_wd-50e-3")
        PrintLine(input, "sledg_mid_hg=sledg_dw_hg+200e-3")
        PrintLine(input, "sledg_up_wd=Swr_wd+Scb_wd")
        PrintLine(input, "sledg_up_hg=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Scb_hg-Al2O3_hg")
        PrintLine(input, "")
        PrintLine(input, "*get,kpnum,kp,0,count")
        PrintLine(input, "k,kpnum+1,Cll_wd-sledg_dw_wd,sledg_dw_hg")
        PrintLine(input, "k,kpnum+2,Cll_wd-sledg_mid_wd,sledg_mid_hg")
        PrintLine(input, "k,kpnum+3,Cll_wd-sledg_up_wd,sledg_up_hg")
        PrintLine(input, "k,kpnum+4,Cll_wd,sledg_up_hg")
        PrintLine(input, "k,kpnum+5,Cll_wd,sledg_dw_hg")
        PrintLine(input, "a,kpnum+1,kpnum+2,kpnum+3,kpnum+4,kpnum+5")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!姘у寲閾濊鐩栧眰鍘氬害 ok")
        PrintLine(input, "rectang,0,Cll_wd-Scb_wd,sledg_up_hg,sledg_up_hg+Al2O3_hg")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬鐐潡 ok")
        PrintLine(input, "rectang,Ad_2ad,Cll_wd-Swr_wd-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD+And_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬閽㈢埅 ok")
        PrintLine(input, "Rod_X=Ad_2ad+(And_wd-Beam_Wd)/2")
        PrintLine(input, "Rod_Y=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD+And_hg-And_in")
        PrintLine(input, "rectang,Rod_X,Rod_X+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod,Rod_X+Rod_2rod+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod*2,Rod_X+Rod_2rod*2+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod*3,Rod_X+Rod_2rod*3+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X,Rod_X+Beam_Wd,Rod_Y+Rod_hg,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+(Beam_Wd-Alrod_wd)/2,Rod_X+(Beam_Wd-Alrod_wd)/2+Alrod_wd,Rod_Y+Rod_hg+Beam_hg,Rod_Y+Rod_hg+Beam_hg+Alrod_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "aovlap,all")
        PrintLine(input, "aglue,all  ")
        PrintLine(input, "nummrg,kp   ")
        PrintLine(input, "numcmp,all  ")
        PrintLine(input, "alls")
        PrintLine(input, "")
        PrintLine(input, "!***************5.瀹氫箟鍚勬潗鏂欏睘鎬?*************        ")
        PrintLine(input, "!瀹氫箟闃存瀬瀵肩儹绯绘暟姣旂數闃?")
        PrintLine(input, "MPTEMP,1,200,400,600,800,900,1000, ")
        PrintLine(input, "")
        PrintLine(input, "!1 闃存瀬纰冲潡")
        PrintLine(input, "MPDATA,KXX,1,1,10.92,11.84,12.76,13.68,14.14,14.6")
        PrintLine(input, "MPDATA,Kyy,1,1,9.04,9.83,10.33,10.68,10.85,10.97")
        PrintLine(input, "")
        PrintLine(input, "!2 闃存瀬閽㈡")
        PrintLine(input, "MPDATA,KXX,2,1,16.93,16.06,14.94,13.69,13.09,12.40,")
        PrintLine(input, "")
        PrintLine(input, "!3 闃存瀬閽㈡绯?")
        PrintLine(input, "MPDATA,KXX,3,1,2.82,3.34,4.74,7.02,8.16,9.30,")
        PrintLine(input, "")
        PrintLine(input, "!4 闃虫瀬鐐潡")
        PrintLine(input, "MPDATA,KXX,4,1,4.3005,4.63041,4.9678,5.3015,5.4683,5.6352")
        PrintLine(input, "")
        PrintLine(input, "!5 閽㈢埅")
        PrintLine(input, "MPDATA,KXX,5,1,64,53.2,42.4,31.6,26.2,20.8,")
        PrintLine(input, "")
        PrintLine(input, "!6 妲藉府 ")
        PrintLine(input, "MPDATA,KXX,6,1,1.29,1.31,1.34,1.37,1.38,1.39")
        PrintLine(input, "")
        PrintLine(input, "!7 鎹ｉ紦绯?")
        PrintLine(input, "MPDATA,KXX,7,,0.34")
        PrintLine(input, "")
        PrintLine(input, "!8 姘у寲閾濊鐩栨枡")
        PrintLine(input, "MPDATA,kxx,8,,0.8")
        PrintLine(input, "")
        PrintLine(input, "!9 绗洓灞傚唴琛細淇濇俯闃叉笚鏂?")
        PrintLine(input, "MPDATA,KXX,9,1,0.593,0.867,1.141,1.415,1.552,1.689")
        PrintLine(input, "")
        PrintLine(input, "!10 绗笁灞傚唴琛細闅旂儹鑰愮伀鐮?")
        PrintLine(input, "MPDATA,KXX,10,,0.22")
        PrintLine(input, "")
        PrintLine(input, "!11 绗簩灞傚唴琛細淇濇俯鐮?")
        PrintLine(input, "MPDATA,KXX,11,1,0.15,0.19,0.23,0.27,0.29,0.31  ")
        PrintLine(input, "")
        PrintLine(input, "!12 绗竴灞傚唴琛細纭呴吀閽?缁濈儹鏉?")
        PrintLine(input, "MPDATA,KXX,12,,0.055")
        PrintLine(input, "")
        PrintLine(input, "!13 渚ч儴纰冲潡")
        PrintLine(input, "MPDATA,KXX,13,1,36.7,30.61,25.25,21.76,20.53,19.47")
        PrintLine(input, "")
        PrintLine(input, "!14 闃虫瀬閾濆鏉?")
        PrintLine(input, "MPTEMP,1,50,100,200,300,400,500,")
        PrintLine(input, "MPDATA,KXX,14,1,205,206,213,229,248,268   ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!***************6.灏嗗悇闈㈠畾涔変负涓嶅悓鐨勬潗鏂?*************   ")
        PrintLine(input, "ESIZE,0.01,0,  ")
        PrintLine(input, "")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      49 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       1, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,3,5,ORDE,3   ")
        PrintLine(input, "FITEM,5,3   ")
        PrintLine(input, "FITEM,5,23  ")
        PrintLine(input, "FITEM,5,48  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       2, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1")
        PrintLine(input, "")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      24 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       3, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,7,5,ORDE,7   ")
        PrintLine(input, "FITEM,5,7   ")
        PrintLine(input, "FITEM,5,32  ")
        PrintLine(input, "FITEM,5,-33 ")
        PrintLine(input, "FITEM,5,40  ")
        PrintLine(input, "FITEM,5,42  ")
        PrintLine(input, "FITEM,5,44  ")
        PrintLine(input, "FITEM,5,51  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       4, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,19,5,ORDE,8  ")
        PrintLine(input, "FITEM,5,8   ")
        PrintLine(input, "FITEM,5,-15 ")
        PrintLine(input, "FITEM,5,34  ")
        PrintLine(input, "FITEM,5,-39 ")
        PrintLine(input, "FITEM,5,41  ")
        PrintLine(input, "FITEM,5,43  ")
        PrintLine(input, "FITEM,5,45  ")
        PrintLine(input, "FITEM,5,-47 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       5, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      50 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       6, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,3,5,ORDE,3   ")
        PrintLine(input, "FITEM,5,5   ")
        PrintLine(input, "FITEM,5,29  ")
        PrintLine(input, "FITEM,5,-30 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       7, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,2,5,ORDE,2   ")
        PrintLine(input, "FITEM,5,6   ")
        PrintLine(input, "FITEM,5,28  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       8, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,2,5,ORDE,2   ")
        PrintLine(input, "FITEM,5,21  ")
        PrintLine(input, "FITEM,5,-22 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       9, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1 ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,2,5,ORDE,2   ")
        PrintLine(input, "FITEM,5,19  ")
        PrintLine(input, "FITEM,5,-20 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,      10, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1 ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,2,5,ORDE,2   ")
        PrintLine(input, "FITEM,5,17  ")
        PrintLine(input, "FITEM,5,-18 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,      11, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,2,5,ORDE,2   ")
        PrintLine(input, "FITEM,5,1   ")
        PrintLine(input, "FITEM,5,-2  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,      12, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1 ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,5,5,ORDE,4   ")
        PrintLine(input, "FITEM,5,4   ")
        PrintLine(input, "FITEM,5,25  ")
        PrintLine(input, "FITEM,5,-27 ")
        PrintLine(input, "FITEM,5,31  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,      13, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      16 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,      14, ,   2,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!***************7.寮€濮嬬綉鏍煎垝鍒?*************      ")
        PrintLine(input, "MSHKEY,0")
        PrintLine(input, "FLST,5,17,5,ORDE,8  ")
        PrintLine(input, "FITEM,5,1   ")
        PrintLine(input, "FITEM,5,-3  ")
        PrintLine(input, "FITEM,5,17  ")
        PrintLine(input, "FITEM,5,-26 ")
        PrintLine(input, "FITEM,5,29  ")
        PrintLine(input, "FITEM,5,-30 ")
        PrintLine(input, "FITEM,5,48  ")
        PrintLine(input, "FITEM,5,-49 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CHKMSH,'AREA'   ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "AMESH,_Y1    ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "CMDELE,_Y2  ")
        PrintLine(input, "")
        PrintLine(input, "FLST,5,34,5,ORDE,8  ")
        PrintLine(input, "FITEM,5,4   ")
        PrintLine(input, "FITEM,5,-16 ")
        PrintLine(input, "FITEM,5,27  ")
        PrintLine(input, "FITEM,5,-28 ")
        PrintLine(input, "FITEM,5,31  ")
        PrintLine(input, "FITEM,5,-47 ")
        PrintLine(input, "FITEM,5,50  ")
        PrintLine(input, "FITEM,5,-51 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CHKMSH,'AREA'   ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "AMESH,_Y1   ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "CMDELE,_Y2 ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!***************8.杈圭晫鏉′欢**************  ")
        PrintLine(input, "/SOL")
        PrintLine(input, "alls")
        PrintLine(input, "LSEL,S,LOC,Y,0  ")
        PrintLine(input, "cm,line_bt,line                   !妲藉簳閮?")
        PrintLine(input, "alls")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "FLST,5,4,4,ORDE,4   ")
        PrintLine(input, "FITEM,5,1   ")
        PrintLine(input, "FITEM,5,66  ")
        PrintLine(input, "FITEM,5,71  ")
        PrintLine(input, "FITEM,5,76 ")
        PrintLine(input, "LSEL,S, , ,P51X ")
        PrintLine(input, "cm,line_sdb,line                   !鑰愮伀鏉愭枡淇濇俯鍖?")
        PrintLine(input, " ")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "FLST,5,5,4,ORDE,5   ")
        PrintLine(input, "FITEM,5,3   ")
        PrintLine(input, "FITEM,5,24  ")
        PrintLine(input, "FITEM,5,26  ")
        PrintLine(input, "FITEM,5,87  ")
        PrintLine(input, "FITEM,5,91")
        PrintLine(input, "LSEL,S, , ,P51X ")
        PrintLine(input, "cm,line_bar,line                   !闃存瀬涓庨槾鏋侀挗妫掑尯 ")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "FLST,5,2,4,ORDE,2   ")
        PrintLine(input, "FITEM,5,93  ")
        PrintLine(input, "FITEM,5,101")
        PrintLine(input, "LSEL,S, , ,P51X ")
        PrintLine(input, "cm,line_sdt,line                   !鐔斾綋鍖?")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "FLST,5,21,4,ORDE,21 ")
        PrintLine(input, "FITEM,5,4   ")
        PrintLine(input, "FITEM,5,11  ")
        PrintLine(input, "FITEM,5,13  ")
        PrintLine(input, "FITEM,5,15  ")
        PrintLine(input, "FITEM,5,17  ")
        PrintLine(input, "FITEM,5,-18 ")
        PrintLine(input, "FITEM,5,27  ")
        PrintLine(input, "FITEM,5,34  ")
        PrintLine(input, "FITEM,5,43  ")
        PrintLine(input, "FITEM,5,60  ")
        PrintLine(input, "FITEM,5,64  ")
        PrintLine(input, "FITEM,5,-65 ")
        PrintLine(input, "FITEM,5,95  ")
        PrintLine(input, "FITEM,5,103 ")
        PrintLine(input, "FITEM,5,-104")
        PrintLine(input, "FITEM,5,107 ")
        PrintLine(input, "FITEM,5,-108")
        PrintLine(input, "FITEM,5,111 ")
        PrintLine(input, "FITEM,5,114 ")
        PrintLine(input, "FITEM,5,116 ")
        PrintLine(input, "FITEM,5,119")
        PrintLine(input, "LSEL,S, , ,P51X ")
        PrintLine(input, "cm,line_tp,line                !椤堕儴  ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "cmsel,s,line_bt ")
        PrintLine(input, "SFL,all,CONV,conv_bt, ,Ta,            !鐐夊簳")
        PrintLine(input, "allsel,all,line")
        PrintLine(input, "")
        PrintLine(input, "cmsel,s,line_sdt ")
        PrintLine(input, "SFL,all,CONV,conv_sdt, ,Ta,           !鐔斾綋鍖?")
        PrintLine(input, "allsel,all,line")
        PrintLine(input, "")
        PrintLine(input, "cmsel,s,line_bar ")
        PrintLine(input, "SFL,all,CONV,conv_bar, ,Ta,           !闃存瀬鍖?")
        PrintLine(input, "allsel,all,line")
        PrintLine(input, "")
        PrintLine(input, "cmsel,s,line_sdb ")
        PrintLine(input, "SFL,all,CONV,conv_sdb, ,Ta,           !鑰愮伀鍙婁繚娓╁尯 ")
        PrintLine(input, "allsel,all,line")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "cmsel,s,line_tp ")
        PrintLine(input, "SFL,all,CONV,conv_tp, ,Td,      !鐐夐《")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "FLST,2,7,4,ORDE,7   ")
        PrintLine(input, "FITEM,2,6   ")
        PrintLine(input, "FITEM,2,-7  ")
        PrintLine(input, "FITEM,2,9   ")
        PrintLine(input, "FITEM,2,33  ")
        PrintLine(input, "FITEM,2,36  ")
        PrintLine(input, "FITEM,2,38  ")
        PrintLine(input, "FITEM,2,142 ")
        PrintLine(input, "DL,P51X, ,TEMP,Tb,0 ")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "")
        PrintLine(input, "!***************9.鐑満姹傝В**************  ")
        PrintLine(input, "SOLVE   ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!***************10.缁撴灉鍚庡鐞?*************  ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "/RGB,INDEX,100,100,100,0")
        PrintLine(input, "/RGB,INDEX,0,0,0,15 ")
        PrintLine(input, "/REPLOT ")
        PrintLine(input, "/CMAP,_TEMPCMAP_,CMP")
        PrintLine(input, "/DELETE,_TEMPCMAP_,CMP  ")
        PrintLine(input, "/SHOW,CLOSE ")
        PrintLine(input, "/DEVICE,VECTOR,0")
        PrintLine(input, "")
        PrintLine(input, "!*  ")
        PrintLine(input, "/POST1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, " ")
        PrintLine(input, "")
        PrintLine(input, "/EFACET,1   ")
        PrintLine(input, "PLNSOL, TEMP,, 0  ")
        PrintLine(input, "/CMAP,_TEMPCMAP_,CMP,,SAVE  ")
        PrintLine(input, "/show,png")
        PrintLine(input, "")
        PrintLine(input, "/EFACET,1   ")
        PrintLine(input, "PLNSOL, TEMP,, 0  ")
        PrintLine(input, "/show,close")
        PrintLine(input, "!*  ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!/RENAME,sxd000,jpg, ,sxd111,,")
        PrintLine(input, "")
        PrintLine(input, "Finish")
        PrintLine(input, "/clear")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "")



        '往下是电场部分的仿真apdl
        PrintLine(input, "/PREP7  ")
        PrintLine(input, "!*********瀹氫箟鍗曞厓*************")
        PrintLine(input, "ET,1,PLANE230   ")
        PrintLine(input, "")
        PrintLine(input, "!*********瀹氫箟鐢甸樆鐜?************")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,1,,2.34e-7  ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,2,,5.52e-5  ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,3,,4.553e-5")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,4,,1.2e-3   ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,5,,2.45e-5  ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,6,,5.65e-6 ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,7,,4.781e-7 ")
        PrintLine(input, "MPTEMP,,,,,,,,  ")
        PrintLine(input, "MPTEMP,1,0  ")
        PrintLine(input, "MPDATA,RSVX,8,,5e10 ")
        PrintLine(input, "")
        PrintLine(input, "!*********鍑犱綍灏哄鍙傛暟**********")
        PrintLine(input, "!妲藉搴k")
        PrintLine(input, "Cll_wd=2020e-3")
        PrintLine(input, "")
        PrintLine(input, "!妲借啗瀹藉害 ok")
        PrintLine(input, "Cv_wd=1940e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗竴灞傚唴琛細纭呴吀閽欐澘 ok")
        PrintLine(input, "Lining1_hg=100e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗簩灞傚唴琛細淇濇俯鐮?鑰愰珮娓╃閰搁挋鏉?ok")
        PrintLine(input, "Lining2_hg=66e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗笁灞傚唴琛細闅旂儹鑰愮伀鐮?ok")
        PrintLine(input, "Lining3_hg=66e-3")
        PrintLine(input, "")
        PrintLine(input, "!绗洓灞傚唴琛細闃叉笚鏂?ok")
        PrintLine(input, "Lining4_hg=185e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡楂樺害ok")
        PrintLine(input, "Cllb_hg=180e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡闀垮害 ok")
        PrintLine(input, "Cllb_wd=2130e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬閽㈡绯婇珮搴?ok")
        PrintLine(input, "Clpt_hg=20e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬鐐潡瀹藉害 ok")
        PrintLine(input, "Cth_wd=1680e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃存瀬鐐潡楂樺害 ok")
        PrintLine(input, "Cth_hg=450e-3")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡楂樺害")
        PrintLine(input, "Scb_hg=820e-3")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡瀹藉害 ok")
        PrintLine(input, "Scb_wd=80e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婇珮搴?ok")
        PrintLine(input, "dgh_hg=550e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婁笂瀹?ok")
        PrintLine(input, "dgh_wd=50e-3")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｅ浐绯婁笅瀹?ok")
        PrintLine(input, "dgh_wd_dwn=260e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬瀹藉害 ok")
        PrintLine(input, "And_wd=1550e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬楂樺害 ok")
        PrintLine(input, "And_hg=370e-3 ")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬璺濅腑蹇冪嚎 ok")
        PrintLine(input, "Ad_2ad=90e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬璺濈渚ч儴鐐潡锛屽ぇ闈㈠姞宸ヨ窛绂?ok")
        PrintLine(input, "Swr_wd=300e-3")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬閽㈡鎻掑叆闃虫瀬娣卞害 ok")
        PrintLine(input, "And_in=100e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅闂磋窛 ok")
        PrintLine(input, "Rod_2rod=300e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅楂樺害 ok")
        PrintLine(input, "Rod_hg=280e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅瀹藉害 ok")
        PrintLine(input, "Rod_dia=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!閽㈢埅姊侀珮搴?ok")
        PrintLine(input, "Beam_hg=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!妯瀹藉害")
        PrintLine(input, "Beam_Wd=1050e-3")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!閾濆鏉嗗 ok")
        PrintLine(input, "Alrod_wd=150e-3")
        PrintLine(input, "")
        PrintLine(input, "!閾濆鏉嗛珮搴?ok")
        PrintLine(input, "Alrod_hg=400e-3")
        PrintLine(input, "")
        PrintLine(input, "!姘у寲閾濊鐩栨枡鍘氬害ok")
        PrintLine(input, "Al2O3_hg=175e-3")
        PrintLine(input, "")
        PrintLine(input, "!閾濇按骞?ok")
        PrintLine(input, "Alu_hg=200e-3            ")
        PrintLine(input, "")
        PrintLine(input, "!鐢佃В璐ㄦ按骞?ok")
        PrintLine(input, "Elu_hg=175e-3   ")
        PrintLine(input, "")
        PrintLine(input, "!鏋佽窛 ok")
        PrintLine(input, "ACD=45e-3")
        PrintLine(input, "                                                          ")
        PrintLine(input, "!鍐呰‖寤烘āok")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg")
        PrintLine(input, "rectang,0,Cllb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Clpt_hg")
        PrintLine(input, "rectang,0,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!渚ч儴鐐潡ok")
        PrintLine(input, "rectang,Cll_wd-Scb_wd,Cll_wd,0,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Scb_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!鎹ｉ紦绯?ok")
        PrintLine(input, "*get,kpnum,kp,0,count")
        PrintLine(input, "k,kpnum+1,Cll_wd-dgh_wd_dwn-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "k,kpnum+2,Cll_wd-dgh_wd_dwn-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "k,kpnum+3,Cll_wd-dgh_wd-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+dgh_hg")
        PrintLine(input, "k,kpnum+4,Cll_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+dgh_hg")
        PrintLine(input, "k,kpnum+5,Cll_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg")
        PrintLine(input, "a,kpnum+1,kpnum+2,kpnum+3,kpnum+4,kpnum+5")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!妲藉府")
        PrintLine(input, "sledg_dw_wd=20e-3+dgh_wd_dwn+Scb_wd")
        PrintLine(input, "sledg_dw_hg=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg")
        PrintLine(input, "sledg_mid_wd=dgh_wd_dwn+Scb_wd-50e-3")
        PrintLine(input, "sledg_mid_hg=sledg_dw_hg+200e-3")
        PrintLine(input, "sledg_up_wd=Swr_wd+Scb_wd")
        PrintLine(input, "sledg_up_hg=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cllb_hg+Scb_hg-Al2O3_hg")
        PrintLine(input, "")
        PrintLine(input, "*get,kpnum,kp,0,count")
        PrintLine(input, "k,kpnum+1,Cll_wd-sledg_dw_wd,sledg_dw_hg")
        PrintLine(input, "k,kpnum+2,Cll_wd-sledg_mid_wd,sledg_mid_hg")
        PrintLine(input, "k,kpnum+3,Cll_wd-sledg_up_wd,sledg_up_hg")
        PrintLine(input, "k,kpnum+4,Cll_wd,sledg_up_hg")
        PrintLine(input, "k,kpnum+5,Cll_wd,sledg_dw_hg")
        PrintLine(input, "a,kpnum+1,kpnum+2,kpnum+3,kpnum+4,kpnum+5")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!姘у寲閾濊鐩栧眰鍘氬害 ok")
        PrintLine(input, "rectang,0,Cll_wd-Scb_wd,sledg_up_hg,sledg_up_hg+Al2O3_hg")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬鐐潡 ok")
        PrintLine(input, "rectang,Ad_2ad,Cll_wd-Swr_wd-Scb_wd,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD,Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD+And_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "!闃虫瀬閽㈢埅 ok")
        PrintLine(input, "Rod_X=Ad_2ad+(And_wd-Beam_Wd)/2")
        PrintLine(input, "Rod_Y=Lining1_hg+Lining2_hg+Lining3_hg+Lining4_hg+Cth_hg+Alu_hg+ACD+And_hg-And_in")
        PrintLine(input, "rectang,Rod_X,Rod_X+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod,Rod_X+Rod_2rod+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod*2,Rod_X+Rod_2rod*2+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+Rod_2rod*3,Rod_X+Rod_2rod*3+Rod_dia,Rod_Y,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X,Rod_X+Beam_Wd,Rod_Y+Rod_hg,Rod_Y+Rod_hg+Beam_hg")
        PrintLine(input, "rectang,Rod_X+(Beam_Wd-Alrod_wd)/2,Rod_X+(Beam_Wd-Alrod_wd)/2+Alrod_wd,Rod_Y+Rod_hg+Beam_hg,Rod_Y+Rod_hg+Beam_hg+Alrod_hg")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "alls")
        PrintLine(input, "aovlap,all")
        PrintLine(input, "aglue,all  ")
        PrintLine(input, "nummrg,kp   ")
        PrintLine(input, "numcmp,all  ")
        PrintLine(input, "alls")
        PrintLine(input, "")
        PrintLine(input, "LSTR,      29,      17  ")
        PrintLine(input, "FLST,2,8,4  ")
        PrintLine(input, "FITEM,2,144 ")
        PrintLine(input, "FITEM,2,33  ")
        PrintLine(input, "FITEM,2,38  ")
        PrintLine(input, "FITEM,2,9   ")
        PrintLine(input, "FITEM,2,36  ")
        PrintLine(input, "FITEM,2,7   ")
        PrintLine(input, "FITEM,2,6   ")
        PrintLine(input, "FITEM,2,142 ")
        PrintLine(input, "AL,P51X ")
        PrintLine(input, "FLST,2,52,5,ORDE,2  ")
        PrintLine(input, "FITEM,2,1   ")
        PrintLine(input, "FITEM,2,-52 ")
        PrintLine(input, "AGLUE,P51X  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      52 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "FLST,5,20,5,ORDE,8  ")
        PrintLine(input, "FITEM,5,8   ")
        PrintLine(input, "FITEM,5,-16 ")
        PrintLine(input, "FITEM,5,34  ")
        PrintLine(input, "FITEM,5,-39 ")
        PrintLine(input, "FITEM,5,41  ")
        PrintLine(input, "FITEM,5,43  ")
        PrintLine(input, "FITEM,5,45  ")
        PrintLine(input, "FITEM,5,-47 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "FLST,5,20,5,ORDE,8  ")
        PrintLine(input, "FITEM,5,8   ")
        PrintLine(input, "FITEM,5,-16 ")
        PrintLine(input, "FITEM,5,34  ")
        PrintLine(input, "FITEM,5,-39 ")
        PrintLine(input, "FITEM,5,41  ")
        PrintLine(input, "FITEM,5,43  ")
        PrintLine(input, "FITEM,5,45  ")
        PrintLine(input, "FITEM,5,-47 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "")
        PrintLine(input, "!********灏嗗悇闈㈠畾涔変负涓嶅悓鐨勬潗鏂?**********")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       1, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FLST,5,7,5,ORDE,7   ")
        PrintLine(input, "FITEM,5,7   ")
        PrintLine(input, "FITEM,5,32  ")
        PrintLine(input, "FITEM,5,-33 ")
        PrintLine(input, "FITEM,5,40  ")
        PrintLine(input, "FITEM,5,42  ")
        PrintLine(input, "FITEM,5,44  ")
        PrintLine(input, "FITEM,5,51  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       2, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      52 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       3, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FLST,5,5,5,ORDE,4   ")
        PrintLine(input, "FITEM,5,4   ")
        PrintLine(input, "FITEM,5,25  ")
        PrintLine(input, "FITEM,5,-27 ")
        PrintLine(input, "FITEM,5,31  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       2, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FLST,5,4,5,ORDE,4   ")
        PrintLine(input, "FITEM,5,5   ")
        PrintLine(input, "FITEM,5,29  ")
        PrintLine(input, "FITEM,5,-30 ")
        PrintLine(input, "FITEM,5,50  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       4, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      49 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       5, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,      24 ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       6, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FLST,5,3,5,ORDE,3   ")
        PrintLine(input, "FITEM,5,3   ")
        PrintLine(input, "FITEM,5,23  ")
        PrintLine(input, "FITEM,5,48  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       7, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FLST,5,10,5,ORDE,6  ")
        PrintLine(input, "FITEM,5,1   ")
        PrintLine(input, "FITEM,5,-2  ")
        PrintLine(input, "FITEM,5,6   ")
        PrintLine(input, "FITEM,5,17  ")
        PrintLine(input, "FITEM,5,-22 ")
        PrintLine(input, "FITEM,5,28  ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMSEL,S,_Y1 ")
        PrintLine(input, "AATT,       8, ,   1,       0,  ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "")
        PrintLine(input, "!********4.缃戞牸鍒掑垎鍜岃竟鐣屾潯浠?**********")
        PrintLine(input, "ESIZE,0.01,0,   ")
        PrintLine(input, "MSHKEY,0")
        PrintLine(input, "FLST,5,52,5,ORDE,2  ")
        PrintLine(input, "FITEM,5,1   ")
        PrintLine(input, "FITEM,5,-52 ")
        PrintLine(input, "CM,_Y,AREA  ")
        PrintLine(input, "ASEL, , , ,P51X ")
        PrintLine(input, "CM,_Y1,AREA ")
        PrintLine(input, "CHKMSH,'AREA'   ")
        PrintLine(input, "CMSEL,S,_Y  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "AMESH,_Y1   ")
        PrintLine(input, "!*  ")
        PrintLine(input, "CMDELE,_Y   ")
        PrintLine(input, "CMDELE,_Y1  ")
        PrintLine(input, "CMDELE,_Y2  ")
        PrintLine(input, "!*  ")
        PrintLine(input, "FINISH  ")
        PrintLine(input, "/SOL")
        PrintLine(input, "LPLOT   ")
        PrintLine(input, "FLST,2,1,4,ORDE,1   ")
        PrintLine(input, "FITEM,2,18  ")
        PrintLine(input, "/GO ")
        PrintLine(input, "!*  ")
        PrintLine(input, "DL,P51X, ,VOLT,0")
        PrintLine(input, "")
        PrintLine(input, "NPLOT   ")
        PrintLine(input, "FLST,2,37,1,ORDE,3  ")
        PrintLine(input, "FITEM,2,6487")
        PrintLine(input, "FITEM,2,6509")
        PrintLine(input, "FITEM,2,-6544   ")
        PrintLine(input, "/GO ")
        PrintLine(input, "!*  ")
        PrintLine(input, "F,P51X,AMPS,-300000/26/4 ")
        PrintLine(input, "/STATUS,SOLU")
        PrintLine(input, "")
        PrintLine(input, "!***************9.姹傝В**************  ")
        PrintLine(input, "SOLVE   ")
        PrintLine(input, "")
        PrintLine(input, "!***************10.缁撴灉鍚庡鐞?************* ")
        PrintLine(input, "")
        PrintLine(input, "/EFACET,1   ")
        PrintLine(input, "PLNSOL, VOLT,, 0")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "/RGB,INDEX,100,100,100,0")
        PrintLine(input, "/RGB,INDEX,0,0,0,15 ")
        PrintLine(input, "/REPLOT ")
        PrintLine(input, "/CMAP,_TEMPCMAP_,CMP")
        PrintLine(input, "/DELETE,_TEMPCMAP_,CMP  ")
        PrintLine(input, "/SHOW,CLOSE ")
        PrintLine(input, "/DEVICE,VECTOR,0")
        PrintLine(input, "")
        PrintLine(input, "!*  ")
        PrintLine(input, "/POST1  ")
        PrintLine(input, "!*  ")
        PrintLine(input, " ")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "/EFACET,1   ")
        PrintLine(input, "PLNSOL, VOLT,, 0")
        PrintLine(input, "")
        PrintLine(input, "/show,png")
        PrintLine(input, "")
        PrintLine(input, "")
        PrintLine(input, "/EFACET,1   ")
        PrintLine(input, "PLNSOL, VOLT,, 0")
        PrintLine(input, "")
        PrintLine(input, "/show,close")
        PrintLine(input, "/RENAME,file000,png,鈥?sxd111,,鈥?")
        PrintLine(input, "!*  ")


        FileClose(input)

        '调用ansys计算
        Dim x As Integer
        x = Shell(Me.ansys启动程序.Text & " -p ansys -np 2 -lch -dir " & Me.工作目录.Text & " -j " & Me.项目名称.Text & " -s read -l en-us -b -i " & Me.工作目录.Text & "\input.mac" & " -o " & Me.工作目录.Text & "\output.mac", 1, False, -1)

    End Sub


    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles 显示Button.Click
        Dim pict1, pict2, pict3 As String
        pict1 = Me.工作目录.Text & "\" & Me.项目名称.Text & "000.png"
        pict2 = Me.工作目录.Text & "\" & Me.项目名称.Text & "001.png"

        Me.PictureBox2.Image = Image.FromFile(pict2)
        Me.PictureBox3.Image = Image.FromFile(pict1)


        Me.Show()
    End Sub

End Class